### ISSUE TITLE
M-Q adds extra /* in /* */ style comments

### ISSUE THREAD

**Issue by benkasminbullock** [dominikh/go-mode.el#91] opened 2015-07-21 00:30 UTC
I am using Emacs 2.45, and the most recent version of go-mode.el. In Go mode, M-Q sometimes adds an extra /*

<pre>
/* isgb returns true if the decomposition is valid for GB (simplified Chinese).

This has a couple of issues. */
</pre>

Put the pointer on the first /\* without selecting a region, and It comes out like this;

<pre>
/* isgb returns true if the decomposition is valid for GB (simplified
/* Chinese).

This has a couple of issues. */
</pre>

If the whole paragraph is selected first and then M-Q is pressed, you get a different result:

<pre>
/* isgb returns true if the decomposition is valid for GB (simplified
Chinese).

This has a couple of issues. */
</pre>

Is it possible to co-opt c-fill-paragraph from lisp/progmodes/cc-cmds.el in the emacs distribution for these kinds of comments?

Incidentally I also tested this is not a setup bug by running 

```
 emacs -Q gbdecomp.go
```

and then importing go-mode.el and using eval-buffer, then switching on go-mode in the gbdecomp.go buffer using M-x go-mode. The comment indenting was the same.

**Comment by dominikh** [comment] 2015-07-21 03:34
I'm afraid this isn't a trivial problem. Using c-fill-paragraph directly isn't really an option because it depends on a lot of cc-mode's parsing and state. We can't copy and modify the function either, because of legal reasons. 

Emacs itself doesn't allow us to specify more than one kind of comment starter/ender, or fill-paragraph would just work. The issue is that Emacs's adaptive fill prefix is aware of comment starters, but we're using "//", not "/*" (so that things like comment-region etc do the right thing). It thus sees /* like any other prefix (like for example "- "). Maybe there's a simple solution to override the prefix detection, but I haven't found it yet.

I'm not seeing a straightforward solution to this problem, and I don't currently have the time to implement my own fill-paragraph for what is a rather rarely used comment style in Go that has an acceptable workaround (filling a region instead of a paragraph).

Outside help would be appreciated, however.

**Comment by bassu** [comment] 2015-12-09 03:04
I'll have to agree with @dominikh cause I don't recall seeing multiline comment style being used anywhere in stdlib. It's just a C thing.

**Comment by yuutayamada** [comment] 2016-01-26 19:05
Hi @dominikh, I wrote this package: https://github.com/yuutayamada/commenter to
set single/multi line comment variables. feel free to comment if you interested:)

**Comment by dominikh** [comment] 2016-01-29 09:57
@yuutayamada Thanks. I'm unlikely to use your package as is (in particular because it doesn't actually work correctly with `fill-paragraph`, because `fill-paragraph` doesn't call `comment-normalize-vars`. You did, however, give me the idea on how to fix this issue: advise `fill-paragraph` (or whatever the correct subroutine is) and set the comment markers depending on the style of comment we're in. Thanks.

**Comment by yuutayamada** [comment] 2016-01-29 21:05
Hi @dominikh, thanks helpful comment. Sorry, I was commented
without seeing fill-paragraph's code because when I called M-x
fill-paragraph inside multi line comment on go-mode, it worked (I
mean there is no extra "/*" inserted).

But yes, probably your concern is right. I noticed fill-paragraph
is calling `fill-comment-paragraph`, which call
`comment-normalize-vars` inside the function, but there is guard
condition and it's including comment-start and comment-end.
So, in some situation like after changed to multi-line comment
variables, the `fill-comment-paragraph` function might be ignored.
(I'm not sure why my function still working correctly though,
calling other fill function, which call `comment-normalize-vars`?)

Anyway for quick fix for this issue, as you wrote, advising
specific function with wrapping comment vars should be worked.
Actually I implemented that way before I found
`comment-normalize-vars`.

**Comment by yuutayamada** [comment] 2016-01-29 21:12
for clarification, I checked below multi line comment with `fill-paragraph`
(I'm less go user, so I worried trivial mistake)
```go
/*
foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo  foo foo
*/
```

Above multi line comment turned to:
```go
/* foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo
foo foo foo foo foo */
```

**Comment by yuutayamada** [comment] 2016-01-29 22:05
just for your information,
I realized my package doesn't work well with `fill-paragraph` and
single line long comment. (`fill-comment-paragraph` didn't
called after I invoked fill-paragraph on multi line comment)
So, I also added an advice to `fill-paragraph` to set comment
variables and now I seem it's working well both single line and
multi line comment. Not sure you are still interested in my package though

**Closed** 2019-08-30 21:44 UTC
Labels: bug

**Comment by benkasminbullock** [comment] 2019-08-30 23:15
Thank you for doing this work, I have confirmed that this fixes the original bug mentioned above.
