### ISSUE TITLE
where I type godef-jump (C-c C-j)

### ISSUE THREAD

**Issue by bowenchen6** [dominikh/go-mode.el#194] opened 2017-06-02 02:59 UTC
something happen:
symbol function definition is void: xref-push-marker-stack

can you give me some help!

**Comment by emirozer** [comment] 2017-06-23 09:20
Hi,

I am having the same issue lately, 'godef-jump fails with the OP's message.

godef is up to date as of opening this issue and in GOPATH.
This is what i have in my .emacs.d

```
(add-hook 'go-mode-hook (lambda ()
                          (setq gofmt-command "goimports")
                          (local-set-key (kbd "C-.") 'godef-jump)
                          (add-hook 'before-save-hook 'gofmt-before-save)
                          (add-hook 'go-mode-hook 'go-eldoc-setup)
                          ))
```


**go version** go1.7.3 linux/amd64
**GNU Emacs** 24.5.1
*go-mode* 20170308.1512

**Comment by dominikh** [comment] 2017-06-26 10:28
@phst This sounds related to your xref commits. Mind having a look?

**Comment by phst** [comment] 2017-06-26 11:04
I can't reproduce this with the current go-mode.el in Emacs 24.5, no matter whether I load the source file or the byte-compiled file. The only reason I can think of is that you attempt to load a go-mode.elc compiled for Emacs 25 in Emacs 24. That's not supported: in general, you can't load a byte-compiled file into an Emacs with a different version number. Please make sure that your go-mode.elc has been compiled with Emacs 24.5 as well.

**Comment by emirozer** [comment] 2017-07-12 12:15
@dominikh @phst I just installed emacs 25.2.2 and it works properly for me.
But this does tell me there is something wrong with go-mode code related to xref usage ? because what @phst said doesn't apply to me as i never compile any packages by hand but only install from melpa.

**Comment by jackbearheart** [comment] 2017-08-21 19:09
I had this error running Emacs 24.5.1. I thought I had everything compiled normally, but probably at some point I compiled the wrong version of go-mode.el (i.e. for Emacs 25) either by downloading it manually or from melpa. I blew away all my packages and re-downloaded from melpa. Everything works. I'm not the OP but I'd guess you can close this.

**Comment by dominikh** [comment] 2018-03-27 15:58
As pointed out above, this is likely an issue due to byte compiling and mixing versions. Closing.

**Closed by dominikh** 2018-03-27 15:58 UTC
