### ISSUE TITLE
C-u C-SPC is undefined under go-mode

### ISSUE THREAD

**Issue by indradhanush** [dominikh/go-mode.el#227] opened 2018-01-12 07:36 UTC
Using `C-u C-SPC` is helpful to jump back to the previous mark after executing something like `go-goto-function` but Emacs complains that it is undefined.

I have verified that the keybinding works on my `scratch` buffer.

I'd be happy to work on sending a patch if this issue is verified in `go-mode`.

**Comment by dominikh** [comment] 2018-01-12 21:29
This does not sound like a go-mode issue. `C-u C-SPC` is working fine for me. We do not bind `C-u` or `C-SPC`, so the global mapping should apply.

**Comment by indradhanush** [comment] 2018-01-13 06:30
Any ideas how I could figure out what could be the problem? My go config looks like this:
```
(use-package exec-path-from-shell
  :ensure t
  :config
  (when (memq window-system '(mac ns))
    (exec-path-from-shell-copy-env "GOROOT")
    (exec-path-from-shell-copy-env "GOPATH")))


(use-package go-mode
  :ensure t
  :config
  (setq gofmt-command "goimports")
  (add-hook 'before-save-hook 'gofmt-before-save)
  (setq flycheck-go-build-install-deps 1)
  )

(use-package go-eldoc
  :ensure t
  :config
  (go-eldoc-setup))

(defun go-mode-setup ()
  "Enable configurations for go."
  (add-hook 'before-save-hook 'gofmt-before-save)
  (add-hook 'go-mode-hook (lambda () (local-set-key (kbd "C-.") 'godef-jump)))
  (add-hook 'go-mode-hook (lambda () (local-set-key (kbd "C-u C-.") 'godef-jump-other-window)))
  (add-hook 'go-mode-hook (lambda () (local-set-key (kbd "C-,") 'xref-pop-marker-stack))))

(add-hook 'go-mode-hook 'go-mode-setup)

(use-package go-autocomplete
  :ensure t
  :config
  (require 'auto-complete-config))

(use-package golint
  :ensure t)

(use-package go-guru
  :ensure t)

(use-package go-playground
  :ensure t)


(provide 'go)
```

**Comment by parhamdoustdar** [comment] 2018-01-30 14:50
A few ideas:

1. Does `C-h h C-SPC` say it is defined?
2. Is `C-@` working? `C-@` and `C-SPC` are both assigned to the same function.

As an aside, what I've noticed in general is that when using jump to definitions, people use `M-,`, not `C-u C-SPC` to get back to the place they were.

**Comment by dominikh** [comment] 2018-03-27 15:52
This issue has timed out (on top of not being a problem caused by go-mode.) Closing.

**Closed by dominikh** 2018-03-27 15:52 UTC
