### ISSUE TITLE
go-remove-unused-imports doesn't work

### ISSUE THREAD

**Issue by marcelino-m** [dominikh/go-mode.el#250] opened 2018-06-09 03:17 UTC
Hi!! 

The command `go-remove-unused-imports` not work for me, I have the same issue #221 post by 
@seagle0128,  and the fix that him  propose  works for me.

**Comment by psanford** [comment] 2019-08-05 22:49
I'm going to close this as a duplicate of #221.

**Closed by psanford** 2019-08-05 22:49 UTC
